#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 22 14:48:35 2019

@author: lester
"""

from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
import numpy as np


x = [0, 1, 2, 3, 4, 5]
y = [0, 1, 4, 9, 16, 25]
f = interp1d(x, y, kind='quadratic')

plt.scatter(x, y, marker='x', s=100)

xnew = np.arange(0, 5, 0.1)
ynew = f(xnew)

plt.scatter(xnew, ynew, s=10)
