#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  6 18:17:52 2019

@author: lester
"""

import numpy as np
import matplotlib.pyplot as plt

xp = [1, 2, 3]
fp = [3, 2, 0]
np.interp(2.5, xp, fp)

np.interp([0, 1, 1.5, 2.72, 3.14], xp, fp)

UNDEF = -99.0
test = np.interp(-4, xp, fp, left=0, right=0)

print(test)